import React from "react";
import S_hook from "./hook";
import S_bottleneck from "./bottleneck";
import S_step1_case from "./step1_case";
import S_step1_lag from "./step1_lag";
import S_step1_fix from "./step1_fix";
import S_step2_check from "./step2_check";
import S_step2_case from "./step2_case";
import S_step2_rank from "./step2_rank";
import S_step3_target from "./step3_target";
import S_step3_feed from "./step3_feed";
import S_step4_expand from "./step4_expand";
import S_step4_journey from "./step4_journey";
import S_step4_patience from "./step4_patience";
import S_reality from "./reality";
import S_summary from "./summary";
import S_cta from "./cta";
import S_endcard from "./endcard";

/** scene id → component (generated by scripts/gen_scene_index.mjs). Missing scenes render a fallback title card. */
export const SCENES: Record<string, React.FC> = {
  "hook": S_hook,
  "bottleneck": S_bottleneck,
  "step1_case": S_step1_case,
  "step1_lag": S_step1_lag,
  "step1_fix": S_step1_fix,
  "step2_check": S_step2_check,
  "step2_case": S_step2_case,
  "step2_rank": S_step2_rank,
  "step3_target": S_step3_target,
  "step3_feed": S_step3_feed,
  "step4_expand": S_step4_expand,
  "step4_journey": S_step4_journey,
  "step4_patience": S_step4_patience,
  "reality": S_reality,
  "summary": S_summary,
  "cta": S_cta,
  "endcard": S_endcard,
};
