import React from "react";


/** scene id → component (generated by scripts/gen_scene_index.mjs). Missing scenes render a fallback title card. */
export const SCENES: Record<string, React.FC> = {

};
