// Regenerate src/scenes/index.ts from the scene files that exist (src/scenes/<sceneId>.tsx).
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const dir = path.join(root, "src/scenes");
const tl = JSON.parse(fs.readFileSync(path.join(root, "src/data/timeline.json"), "utf8"));
const idxPath = path.join(dir, "index.ts");

const ids = tl.scenes.map((s) => s.id).filter((id) => fs.existsSync(path.join(dir, `${id}.tsx`)));
const missing = tl.scenes.map((s) => s.id).filter((id) => !ids.includes(id));
const ident = (id) => "S_" + id.replace(/[^A-Za-z0-9_]/g, "_");
const src =
  `import React from "react";\n` +
  ids.map((id) => `import ${ident(id)} from "./${id}";`).join("\n") +
  `\n\n/** scene id → component (generated by scripts/gen_scene_index.mjs). Missing scenes render a fallback title card. */\n` +
  `export const SCENES: Record<string, React.FC> = {\n` +
  ids.map((id) => `  ${JSON.stringify(id)}: ${ident(id)},`).join("\n") +
  `\n};\n`;
fs.writeFileSync(idxPath, src);
console.log(`registered ${ids.length} scenes${missing.length ? `; missing: ${missing.join(", ")}` : ""}`);
